name: cfe_registros
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  get: ^4.6.6
  data_table_2: 2.5.3
  shared_preferences: ^2.5.1
  image_picker: ^1.1.2
  file_picker: ^8.3.3
  intl: ^0.20.2
  printing: ^5.14.2
  pdf: ^3.11.3
  url_launcher: ^6.3.1
  http_parser: ^4.0.2
  excel: ^4.0.6
  file_saver: ^0.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logoCFE.png
    - assets/CFE.jpg
    - assets/cfePDF.png
